site_name: Hanish
repo_name: GitHub
repo_url: https://github.com/bbengfort/hanish
site_description: A slackbot that makes small talk about the weather, powered by Dark Sky.
site_author: Benjamin Bengfort
theme: readthedocs

pages:
    - "Introduction": index.md
    - "Getting Started": walkthrough.md
